defaults:
  - override hydra/launcher: joblib
#   - hydra/sweeper: optuna

# hydra:
#   sweeper:
#     optuna_config:
#       optimized_metric: "train/cumulative_error_step"
#       direction: minimize
#       study_name: one_block
#       storage: null
#       n_trials: 20
#       n_jobs: 20
#       sampler: tpe
#       seed: 123
#   params:
#       model.nn.backbone.num_layers_stage: choice(1, 2, 3, 4, 5)
#       model.nn.backbone.d_model: choice(10, 25, 50, 100, 150)
#       model.optimizer.lr: interval(0.0001, 0.1)

# hydra:
#   mode: "MULTIRUN" # set hydra to multirun by default if this config is attached

#   sweeper:
#     _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

#     optimized_metric: "train/cumulative_error_step"

#     # storage URL to persist optimization results
#     # for example, you can use SQLite if you set 'sqlite:///example.db'
#     storage: null

#     # name of the study to persist optimization results
#     study_name: one_block

#     # number of parallel workers
#     n_jobs: 20

#     # 'minimize' or 'maximize' the objective
#     direction: minimize

#     # total number of runs that will be executed
#     n_trials: 20

#     # choose Optuna hyperparameter sampler
#     # you can choose bayesian sampler (tpe), random search (without optimization), grid sampler, and others
#     # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
#     sampler:
#       _target_: optuna.samplers.TPESampler
#       seed: 1234
#       n_startup_trials: 10 # number of random sampling runs before optimization starts

#     # define hyperparameter search space
#     params:
#       model.nn.backbone.num_layers_stage: choice(1, 2, 3, 4, 5)
#       model.nn.backbone.d_model: choice(10, 25, 50, 100, 150)
#       model.optimizer.lr: interval(0.0001, 0.1)