logging.path: "./lightning_logs/plus_moe/${dataset.name}"
logging.name: "model=${model._target_}-backbone=${model.nn.backbone._target_}-lr=${model.optimizer.lr}-width=${model.nn.backbone.layer_width}-layers=${model.nn.backbone.num_layers}-loss=${model.loss._target_}-seed=${random.seed}"

dataset._target_: dataset.SvmGuideDataModule
dataset.name: "svmguide3"
dataset.num_workers: 1
dataset.persistent_workers: True
dataset.batch_size: 1

random.seed: !!python/tuple [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]

trainer.max_epochs: 1
trainer.log_every_n_steps: 1
trainer.devices: 1
trainer.accelerator: 'cpu'
trainer.fast_dev_run: False

model._target_: model.OnlineMoE
model.loss._target_: torch.nn.CrossEntropyLoss

model.variance: 0.01
model.temperature: 0.01

model.nn.backbone._target_: modules.MLP
model.nn.backbone.size_in: 21
model.nn.backbone.num_layers: 3
model.nn.backbone.layer_width: 250
model.nn.backbone.n_classes: 2
model.nn.backbone.size_out: 2
model.nn.backbone.dropout: 0.3

model.optimizer._target_: torch.optim.SGD
model.optimizer.lr: 0.001

# taskset -c "0-19" python run_hydra.py --config=config/moe_svm.yaml
