logging.path: "./lightning_logs/ablation_no_backprop/${dataset.name}/${model.nn.backbone.merge}"
logging.name: "model=${model._target_}-backbone=${model.nn.backbone._target_}-lr=${model.optimizer.lr}-width=${model.nn.backbone.layer_width}-layers=${model.nn.backbone.num_layers}-protoBlocks=${model.nn.backbone.num_blocks_stage}-protoWidth=${model.nn.backbone.layer_width_stage}-norm=${model.nn.backbone.norm_inputs}-seed=${random.seed}"

dataset._target_: dataset.SvmGuideDataModule
dataset.name: "svmguide3"
dataset.num_workers: 1
dataset.persistent_workers: True
dataset.batch_size: 1

random.seed: !!python/tuple [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]

trainer.max_epochs: 1
trainer.log_every_n_steps: 1
trainer.devices: 1
trainer.accelerator: 'cpu'
trainer.fast_dev_run: False

trainer.max_epochs: 1
trainer.log_every_n_steps: 1
trainer.devices: 1
trainer.accelerator: 'cpu'
trainer.fast_dev_run: False

model._target_: model.OnlineDeltaBackpropOnly
model.loss._target_: torch.nn.CrossEntropyLoss
model.nn.backbone.merge: "sum"

model.nn.backbone.variance: 1
model.nn.backbone._target_: modules.BackPropOnly
model.nn.backbone.size_in: 1
model.nn.backbone.size_in_MLP: 21
model.nn.backbone.num_layers: 3
model.nn.backbone.layer_width: 250
model.nn.backbone.layer_width_stage: 250
model.nn.backbone.num_blocks_stage: 6
model.nn.backbone.norm_inputs: False

model.nn.backbone.n_classes: 2
model.nn.backbone.size_out: 2
model.nn.backbone.dropout: 0.3

model.optimizer._target_: torch.optim.SGD
# model.optimizer.lr: !!python/tuple [0.005, 0.01]
model.optimizer.lr: 0.03